export interface SetupSpecification {
    idle: number,
    load: number,
    measuringDevice?: string,
    cState?: string,
    motherboard?: string,
    cpu?: string,
    cpuCooler?: string,
    gpu?: string,
    ram?: string,
    bootDrive?: string,
    psu?: string,
    powerAdapter?: string,
    os?: string,
    mouse?: string,
    keyboard?: string,
    monitor?: string,
    user: string,
}