export const input = $state({
    idle: {
        label: "Idle Power",
        value: null,
        type: 'number',
        placeholder: 'Type here',
        tooltip: 'in Watt',
        min: 0,
        steps: 0.1,
    },
    load: {
        label: "Load Power",
        value: null,
        type: 'number',
        placeholder: 'Type here',
        tooltip: 'in Watt',
        min: 0,
        steps: 0.1,
    },
    measuringDevice: {
        label: "Meas. Device",
        value: '',
        type: 'text',
        placeholder: 'Type here',
        tooltip: 'Brand + Modell',
    },
    cState: {
        label: "C-States",
        value: '',
        options: ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9'],
    },
    motherboard: {
        label: "Motherboard",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    cpu: {
        label: "CPU",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    cpuCooler: {
        label: "CPU Cooler",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    gpu: {
        label: "GPU",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    ram: {
        label: "RAM",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    bootDrive: {
        label: "Boot Drive",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    psu: {
        label: "PSU",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    powerAdapter: {
        label: "Power Adapter",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    os: {
        label: "OS",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    mouse: {
        label: "Mouse",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    keyboard: {
        label: "Keyboard",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
    monitor: {
        label: "Monitor",
        value: '',
        type: 'text',
        placeholder: 'Type here',
    },
});

export const parts = {
    measuringDevice: ["Fluke 117", "Keysight 34461A", "Tektronix DMM6500", "Extech EX330"],
    motherboard: ["ASUS ROG Strix Z790-E", "MSI MPG Z790 Carbon", "Gigabyte Z790 AORUS Elite", "ASRock Z790 Steel Legend"],
    cpu: ["Intel Core i5-14600K", "Intel Core i7-14700K", "Intel Core i9-14900K", "AMD Ryzen 5 7600X", "AMD Ryzen 7 7700X", "AMD Ryzen 9 7900X", "AMD Ryzen 9 7950X"],
    cpuCooler: ["Noctua NH-D15", "Corsair iCUE H150i ELITE CAPELLIX", "be quiet! Dark Rock Pro 4", "ARCTIC Liquid Freezer II 280"],
    gpu: ["NVIDIA GeForce RTX 4060", "NVIDIA GeForce RTX 4070", "NVIDIA GeForce RTX 4080", "AMD Radeon RX 7600"],
    ram: ["Corsair Vengeance DDR5-6000", "G.Skill Trident Z5 RGB DDR5-6400", "Kingston FURY Beast DDR5-5600", "Crucial DDR5-4800"],
    bootDrive: ["Samsung 990 PRO 2TB", "WD Black SN850X 1TB", "Crucial P5 Plus 1TB", "Sabrent Rocket 4 Plus 2TB"],
    psu: ["Corsair RM850x", "EVGA SuperNOVA 850 G6", "Seasonic PRIME TX-1000", "be quiet! Dark Power 13 1000W"],
    powerAdapter: ["Anker 737 GaNPrime 120W", "UGREEN Nexode 100W", "Belkin BoostCharge Pro 140W", "Satechi 165W"],
    os: ["Windows 11 Pro", "Windows 11 Home", "Ubuntu 24.04 LTS", "MacOS Sequoia"],
    mouse: ["Logitech G Pro X Superlight", "Razer DeathAdder V3 Pro", "SteelSeries Aerox 5", "Glorious Model O Wireless"],
    keyboard: ["Keychron Q1 Pro", "Logitech G915 TKL", "Razer BlackWidow V4 Pro", "Ducky One 3"],
    monitor: ["LG 27GP950-B", "Samsung Odyssey G7", "ASUS ROG Swift PG32UQX", "Dell Alienware AW3423DWF"],
}
