export const setups = $state([{
    "id": 1,
    "idle": "1.5W",
    "load": "63W",
    "cState": "C8",
    "measuringDevice": "ina219",
    "cpu": "Intel Core i5-9500T",
    "motherboard": "HP 859C",
    "psu": "HP 90W PPP012C-S",
    "powerAdapter": "iGPU",
    "cpuCooler": "-",
    "gpu": "iGPU",
    "ram": "1x8GB F4-2666C19-8GRS DDR4",
    "bootDrive": "Kingston A2000 500GB NVME",
    "os": "Fedora 33",
    "mouse": "Dell Maus",
    "keyboard": "HP Keyboard"
}, {
    "id": 2,
    "idle": "2.3W",
    "load": "6.4W",
    "cState": "?",
    "measuringDevice": "NZR-SEM 16+",
    "cpu": "Intel Atom Z8300",
    "motherboard": "Wintel CX-W8",
    "psu": "ANU-050300A",
    "powerAdapter": "iGPU",
    "cpuCooler": "passiv",
    "gpu": "iGPU",
    "ram": "1 x 2GB DDR3L RAM on Board",
    "bootDrive": "32GB SSD on Board (Kingston)",
    "os": "Win 10 Home 64 Bit",
    "mouse": "Perixx Periboard-515 Plus TK 514U",
    "keyboard": ""
}, {
    "id": 3,
    "idle": "2.4W",
    "load": "8.4W",
    "cState": "C6",
    "measuringDevice": "PM231E",
    "cpu": "Intel Atom Z3736F",
    "motherboard": "Pipo X8 All In One PC",
    "psu": "Keyu KA1433",
    "powerAdapter": "iGPU",
    "cpuCooler": "passiv",
    "gpu": "iGPU",
    "ram": "1x2GB RAM on Board",
    "bootDrive": "Samsung CGND3R 64GB",
    "os": "Win 10 Home 32 Bit",
    "mouse": "Logitech K400",
    "keyboard": "Logitech K400"
}, {
    "id": 4,
    "idle": "2.6W",
    "load": "61W",
    "cState": "C7",
    "measuringDevice": "Energy Check 3000",
    "cpu": "Intel Core i3-8100T",
    "motherboard": "Dell 0NV0M7",
    "psu": "DELL PA-12 65W",
    "powerAdapter": "iGPU",
    "cpuCooler": "Serienkühler aktiv",
    "gpu": "iGPU",
    "ram": "2x8GB GSkill F4-2666C19-8GRS",
    "bootDrive": "Kingston A2000 500GB",
    "os": "Ubuntu Server 20.04",
    "mouse": "Dell Maus",
    "keyboard": "Logitech Keyboard"
}, {
    "id": 5,
    "idle": "3.2W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
}, {
    "id": 6,
    "idle": "3.4W",
    "load": "",
    "cState": "C8",
    "measuringDevice": "KD302",
    "cpu": "Intel Core i5-7500",
    "motherboard": "Asus H110S1",
    "psu": "Voltcraft NPS-150 - 12V",
    "powerAdapter": "iGPU",
    "cpuCooler": "passiv",
    "gpu": "iGPU",
    "ram": "2x8GB Crucial",
    "bootDrive": "Transcend MTS400 M.2 SSD 64GB",
    "os": "Debian Testing XFCE (Bullseye)",
    "mouse": "Mircrosoft Classic IntelliMouse",
    "keyboard": "Logitech G610"
}, {
    "id": 7,
    "idle": "3.5W",
    "load": "17.6W",
    "cState": "C10",
    "measuringDevice": "Energy Logger 4000",
    "cpu": "Intel Pentium J5005",
    "motherboard": "Intel NUC NUC7PJYH",
    "psu": "APD 19V 3,42A",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x4GB HyperX Impact",
    "bootDrive": "Samsung SSD 850 EVO 120GB",
    "os": "Ubuntu Desktop 19.10",
    "mouse": "Logitech Unifying",
    "keyboard": "Logitech Unifying"
}, {
    "id": 8,
    "idle": "3.5W",
    "load": "12.4W",
    "cState": "C8",
    "measuringDevice": "PM231E",
    "cpu": "Intel Celeron 4205U",
    "motherboard": "Shuttle DS10U",
    "psu": "APD DA65A19 19V 1,6A",
    "powerAdapter": "iGPU",
    "cpuCooler": "passiv",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT8G4SFS824A",
    "bootDrive": "Crucial MX500 250GB SATA",
    "os": "Ubuntu 20.04 (5.4.0-26)",
    "mouse": "Logitech Unifying",
    "keyboard": "Logitech Unifying"
}, {
    "id": 9,
    "idle": "3.9W",
    "load": "44.7W",
    "cState": "C7",
    "measuringDevice": "KD302",
    "cpu": "Intel Core i3-8100",
    "motherboard": "Fujitsu D3674-B",
    "psu": "Leicke 12V 150W NT03016",
    "powerAdapter": "iGPU",
    "cpuCooler": "passiv Scythe Samurai ZZ",
    "gpu": "iGPU",
    "ram": "1 x 4GB DDR4-2133",
    "bootDrive": "WD Blue 1TB SATA",
    "os": "Ubuntu 20.04.3",
    "mouse": "Microsoft Wheel Mouse Optical",
    "keyboard": "Logitech K120"
}, {
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},{
    "id": 10,
    "idle": "3.9W",
    "load": "8.3W",
    "cState": "",
    "measuringDevice": "KD302",
    "cpu": "Intel Celeron N2820",
    "motherboard": "Intel NUC DN2820FYKH",
    "psu": "Asian Power Devices 12V 36W",
    "powerAdapter": "iGPU",
    "cpuCooler": "NUC Serienkühler",
    "gpu": "iGPU",
    "ram": "1x8GB Crucial CT102464BF160B",
    "bootDrive": "Samsung SSD 840 Evo 1TB",
    "os": "Win8.1 64bit",
    "mouse": "Logitech Funkdongle",
    "keyboard": "Logitech Funkdongle"
},]);
